### ISSUE TITLE
[bug] PlantDetailPopUpVC에서 횡 스크롤 애니메이션 끊기는 현상 

### ISSUE THREAD

**Issue by snowedev** [TeamCherish/Cherish-iOS#15]
## 🐞 버그 설명
PlantDetailPopUpVC에서 횡 스크롤 애니메이션 끊기는 현상이 있다고 피드백을 받았었는데!
앱잼 마지막 날에 이 부분 내가 했어서 요고 고칠게요~

<img width=30% src=https://user-images.githubusercontent.com/42789819/127762651-519b3b0f-d00d-435b-a8b0-99569f80b19b.jpeg>

## 📝 todo
- [x] pageController user interaction unable
- [x] bug fix

**Comment by hwangJi-dev** [comment]
굿 죠씁니다!
