### ISSUE TITLE
[feat] About Cherish 인스타그램 버튼 추가

### ISSUE THREAD

**Issue by snowedev** [TeamCherish/Cherish-iOS#39]
## 💡 Issue
이슈에 대한 내용을 설명해주세요.

## 📝 todo
- [x] About Cherish에 인스타그램 연결 버튼 추가

**Comment by seohyun-106** [comment]
우와 체리쉬에 인스타그램이 연결되었다니 !
MZ세대에게 정말 딱 맞는 업데이트인걸 ?
믓찌다 믓찌다 울언니 !

![image](https://user-images.githubusercontent.com/61549796/144752475-79aee536-cd97-44c9-88bc-a652f6418d1a.jpeg)

**Comment by snowedev** [comment]
서현씨 PR에 해달라니까 왜 이슈에 코멘트를 하시는거에요 증말

**Comment by seohyun-106** [comment]
아나 모바일 헷갈리네 그냥 봐주라 ㅋ.ㅋ
